// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn-1YEdJolDXxSFJdBnHdbJubgEb-NuDY',
    appId: '1:544877655449:web:ba25f55e6b9b98890acf08',
    messagingSenderId: '544877655449',
    projectId: 'gamevault-steamapimanager',
    authDomain: 'gamevault-steamapimanager.firebaseapp.com',
    storageBucket: 'gamevault-steamapimanager.firebasestorage.app',
    measurementId: 'G-RDMYDKFL6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp_zGa0AIUVqQyawzL1d7jWHVaZy9EE4E',
    appId: '1:544877655449:android:902943ec5671ddd60acf08',
    messagingSenderId: '544877655449',
    projectId: 'gamevault-steamapimanager',
    storageBucket: 'gamevault-steamapimanager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFC3c1HHzfcXmQCvmkb8PRFy5KlLUE8jc',
    appId: '1:544877655449:ios:d5ab68e64be20f4a0acf08',
    messagingSenderId: '544877655449',
    projectId: 'gamevault-steamapimanager',
    storageBucket: 'gamevault-steamapimanager.firebasestorage.app',
    iosBundleId: 'com.example.gameVault',
  );

}